[package]
name = "cubes"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "cubes"
path = "src/main.rs"
test = false
bench = false

[dependencies]
libm = "0.2"
trueos = { path = "../TRUEOS-Blueprints/api", features = ["default-global-allocator", "tokio-net-probe", "ui4-scene"] }
trueos-picasso = { path = "../TRUEOS-Picasso", default-features = false, features = ["blueprint"] }

[build-dependencies]
sha2 = "0.10"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
