// Generated by Cubes/tools/export_patch_driver.py; do not hand edit.
pub(crate) const SOURCE_SHA256: &str = "1166ee9b78e3e502466cc0737c4e0727d4eefbce3336b43284f6bd342f9ed6d2";
pub(crate) const PALETTE_SHA256: &str = "7aec932e786b436b4617d288322b6733ceb06a900e4b07eb95fa95f7bc8d1a0d";
pub(crate) const CONTRACT_VERSION: u32 = 10;
