#!/usr/bin/env python3
"""Bake/check Cubes' reviewed Mandelbox package through TRUEOS' ShaderToy lane."""
from pathlib import Path
import argparse
import hashlib
import json
import struct
import subprocess
import sys
import tempfile
from export_chroma import glsl_source, kernel_source

APP = Path(__file__).resolve().parents[1]
OS = APP.parent / 'TRUEOS'
ASSETS = APP / 'Cube/mandelbox'
NAME = 'shadertoy_mandelbox'
FILES = ('kernel.bin', 'kernel.spv', 'input.glsl', 'kernel.clcpp', 'kernel.manifest.json', 'kernel.contract.rs')
CONTRACT = OS / f'crates/trueos-shader/gpgpu/kernels/artifacts/adls/cpp/{NAME}.contract.rs'
TRUST = OS / 'src/intel/gpgpu/artifacts/shadertoy_mandelbox_package.rs'

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix='cubes-mandelbox-') as directory:
        glsl = glsl_source()
        generated = kernel_source(glsl).encode()
        if args.check:
            assert glsl.encode() == (ASSETS/'input.glsl').read_bytes(), 'stale Chroma port'
            assert generated == (ASSETS/'kernel.clcpp').read_bytes(), 'stale generated C++'
        else:
            (ASSETS/'input.glsl').write_text(glsl)
            (ASSETS/'kernel.clcpp').write_bytes(generated)
            toolchain = OS/'bld/shadertoy-cpp-toolchain/root'
            subprocess.run([sys.executable, str(OS/'tools/intel-gpu-bakery/bake.py'), '--source', str(ASSETS/'kernel.clcpp'), '--artifact-name', NAME, '--profile', str(OS/'tools/intel-gpu-bakery/profiles/adls-4680-r0c-shadertoy.json'), '--variant', 'cpp-native', '--build-root', str(OS/'bld/cubes-mandelbox-bakery'), '--expect-kernel', NAME, '--rust-symbol', NAME+'=SHADERTOY_MANDELBOX_ADLS_CPP_ABI_CONTRACT', '--repro-check', '--clang', str(toolchain/'usr/lib/llvm-21/bin/clang'), '--llvm-spirv', str(toolchain/'usr/bin/llvm-spirv-21'), '--ocloc', str(toolchain/'usr/bin/ocloc-26.05.1')], check=True, cwd=OS)
            baked = OS/f'bld/cubes-mandelbox-bakery/adls/cpp-native/{NAME}/run-a'
            for suffix in ('bin', 'spv', 'manifest.json', 'contract.rs'):
                (ASSETS/f'kernel.{suffix}').write_bytes((baked/f'{NAME}.{suffix}').read_bytes())
    parts = [(ASSETS/file).read_bytes() for file in FILES]
    manifest = json.loads(parts[4])
    source = manifest['source']
    assert next(entry for entry in source['inputs'] if entry['path'] == source['path'])['sha256'] == hashlib.sha256(parts[3]).hexdigest()
    data = b'STPKG01\0' + struct.pack('<6I', *(len(part) for part in parts)) + b''.join(parts)
    digest = ', '.join(f'0x{x:02x}' for x in hashlib.sha256(data).digest())
    trust = '// Generated by Cubes/tools/bake_mandelbox.py. Payload remains Blueprint-owned.\n'
    trust += 'pub(crate) const SHADERTOY_MANDELBOX_PACKAGE: ShaderToyPackageContract = ShaderToyPackageContract {\n'
    trust += f'    shader_id: 16, bytes: {len(data)}, bin_bytes: {len(parts[0])}, spv_bytes: {len(parts[1])},\n    sha256: [{digest}],\n}};\n'
    outputs = {ASSETS/'mandelbox.stpkg': data, ASSETS/'package.sha256': (hashlib.sha256(data).hexdigest()+'\n').encode(), CONTRACT: parts[5], TRUST: trust.encode()}
    for path, expected in outputs.items():
        if args.check:
            assert path.read_bytes() == expected, f'stale {path}'
        else:
            path.write_bytes(expected)
    print(f'Mandelbox: {len(data)} package bytes; source, package and kernel trust agree')

if __name__ == '__main__': main()
