#!/usr/bin/env python3
"""Export the checked, relocation-free gfx120 cube experiment into TRUEOS."""
import argparse
import hashlib
import json
from pathlib import Path
import struct
import re

ROOT = Path(__file__).resolve().parents[1]

def export(bake, output):
    manifest = json.loads((bake / 'manifest.json').read_text())
    assert manifest['compiled_device_id'] in ('0xa780', '0x4680')
    assert manifest['patches'] == 44 and manifest['input_control_points'] == 1
    native = bake / manifest['native_directory']
    for name, digest in manifest['capture_sha256'].items():
        assert hashlib.sha256((native / name).read_bytes()).hexdigest() == digest
    def fields(name):
        return {k: int(v, 0) for k, v in re.findall(r'(\w+)=(0x[0-9a-fA-F]+|\d+)',
            (native / name).read_text())}
    expected = {
        'vertex_TRUEOS_VS_state_v1.txt': dict(verx10=120, dispatch_grf_start=2, urb_entry_64b=1, max_threads=546,
            uses_instanceid=1, vf_packing0=0xa7, binding_table_entries=4, vue_slots=3),
        'fragment_TRUEOS_PS_state_v1.txt': dict(verx10=120, grf_start8=4, num_varying_inputs=1,
            flat_inputs=0, binding_table_entries=1, scratch_bytes=0, push_bytes=0),
        'tess_control_TRUEOS_HS_state_v1.txt': dict(verx10=120, instances=3, urb_entry_64b=2),
        'tess_eval_TRUEOS_DS_state_v1.txt': dict(verx10=120, dispatch_grf_start=5, urb_read_length=15, vue_slots=3),
        'tessellation_TRUEOS_TE_state_v1.txt': dict(domain=1, partitioning=0, output_topology_lower_left=2,
            domain_origin=0, triangle_domain=1),
    }
    for name, values in expected.items():
        actual = fields(name)
        assert all(actual[k] == v for k, v in values.items()), f'unsupported capture: {name}'
    urb = fields('tessellation_TRUEOS_URB_state_v1.txt')
    assert urb['deref_block_size'] == 0
    assert [(urb[f'stage{i}_size'], urb[f'stage{i}_start'], urb[f'stage{i}_entries'])
            for i in range(4)] == [(1,4,2688),(2,25,1152),(1,43,2688),(1,4,0)]
    vs_bindings = next(native.glob('*_vertex_*_bind_map.txt')).read_text()
    assert 'surfaces=4 samplers=0' in vs_bindings
    for slot in range(1, 4):
        assert f'surface[{slot}]=set:0 binding:{slot-1} index:{slot-1} offset:{16*(slot-1)} plane:0' in vs_bindings
    ds_bindings = next(native.glob('*_tess_eval_*_bind_map.txt')).read_text()
    assert 'surfaces=3 samplers=0' in ds_bindings
    assert 'surface[1]=set:0 binding:0 index:0 offset:0 plane:0' in ds_bindings
    assert 'surface[2]=set:0 binding:1 index:1 offset:16 plane:0' in ds_bindings
    codes = {}
    for stage, number in [('vertex', 0), ('tess_control', 1), ('tess_eval', 2), ('fragment', 4)]:
        path = sorted(native.glob(f'*_{stage}_*_shader_serialize.bin'))[0]
        blob = path.read_bytes()
        actual, size = struct.unpack_from('<II', blob)
        prog = struct.unpack_from('<11I', blob, 8 + size)
        assert actual == number and prog[0] == number and prog[7] == size
        assert prog[1:7] == (0,)*6 and prog[8:11] == (0,)*3, 'push/scratch/constants/relocations unsupported'
        assert size % 4 == 0
        codes[stage] = struct.unpack_from(f'<{size//4}I', blob, 8)
    text = '// Generated by Cubes/tools/export_patch_driver.py; do not hand edit.\nuse super::*;\n'
    text += f'pub(crate) const SOURCE_SHA256: &str = "{manifest["source_sha256"]}";\n'
    text += 'pub(crate) const CONTRACT_VERSION: u32 = 7;\n'
    for stage, words in codes.items():
        text += f'pub(crate) static {stage.upper()}: [u32; {len(words)}] = [\n'
        for i in range(0, len(words), 8):
            text += '    ' + ', '.join(f'0x{w:08x}' for w in words[i:i+8]) + ',\n'
        text += '];\n'
    for stage, kind, count in [('tess_control', 'HS', 9), ('tess_eval', 'DS', 11)]:
        lines = (native / f'{stage}_TRUEOS_{kind}_state_v1.txt').read_text().splitlines()
        assert 'verx10=120' in lines[0] and 'scratch_bytes=0' in lines[0]
        words = [int(x,16) for x in lines[1].split()[1:]]
        assert len(words) == count
        # KSP is uploaded in our own instruction BO, never ANV's allocation.
        words[3 if kind == 'HS' else 1] = 0
        if kind == 'DS':
            words[7] |= 1 << 2 # ComputeWCoordinateEnable for the triangle domain.
        text += f'pub(crate) const {kind}_PACKET: [u32; {count}] = [' + ','.join(f'0x{x:08x}' for x in words) + '];\n'
    text += '''
// gfx120 triangle domain, integer partitioning, upper-left origin (CCW),
// reversed triangle patch header with separate inner factor. No distribution.
pub(crate) const TE_PACKET: [u32; 5] = [0x781c0003, 0x00c00311, 0x427c0000, 0x42800000, 0];
// Captured intel_get_urb_config allocation: size64B, start8KiB, entries.
pub(crate) const URB: [(u32,u32,u32); 4] = [(1,4,2688),(2,25,1152),(1,43,2688),(1,4,0)];
const fn kernel(offset: u32, size: u32, grf: u8, bindings: u8) -> ShaderKernelMetadata {
    ShaderKernelMetadata { code_offset_bytes: offset, code_size_bytes: size,
        code_alignment_bytes: 64, ksp_offset_bytes: 0, dispatch_mode: DispatchMode::Simd8,
        grf_start_register: grf, grf_used: 128, push_constant_bytes: 0,
        binding_table_entry_count: bindings, sampler_count: 0 }
}
pub(crate) static PIPELINE: TrianglePipeline = TrianglePipeline {
    vs: TriangleVertexShader { code: &VERTEX, meta: TriangleVertexShaderMetadata {
        kernel: kernel(0, VERTEX.len() as u32 * 4, 2, 4), max_threads: 546,
        urb_entry_output_length: 1 } },
    ps: TrianglePixelShader { code: &FRAGMENT, meta: TrianglePixelShaderMetadata {
        kernel: kernel(((VERTEX.len() as u32 * 4) + 63) & !63, FRAGMENT.len() as u32 * 4, 4, 1),
        num_varying_inputs: 1, uses_vmask: true, computed_stencil: false,
        persample_dispatch: false, computed_depth_mode: 0, flat_inputs: 0 } },
};
pub(crate) fn matches(pipeline: &TrianglePipeline) -> bool {
    core::ptr::eq(pipeline.vs.code.as_ptr(), VERTEX.as_ptr())
        && core::ptr::eq(pipeline.ps.code.as_ptr(), FRAGMENT.as_ptr())
}
'''
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text)
    # Blueprint source overlays contain the app but not the sibling TRUEOS
    # checkout. Keep the source hash beside the reference asset so build.rs
    # can still validate the exported bundle after overlaying the app.
    (ROOT / 'Cube' / 'cube_driver_manifest.rs').write_text(
        f'// Generated by Cubes/tools/export_patch_driver.py; do not hand edit.\n'
        f'pub(crate) const SOURCE_SHA256: &str = "{manifest["source_sha256"]}";\n'
        f'pub(crate) const CONTRACT_VERSION: u32 = 7;\n'
    )

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('bake', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    export(args.bake, args.output)
