#!/usr/bin/env python3
"""Export the exact CubeImage/reference GLB into small indexed Rust geometry."""
import argparse
import hashlib
from pathlib import Path
from bake_patch_cube import geometry
ROOT = Path(__file__).resolve().parents[1]
def source():
    raw, triangles = geometry(ROOT/'Cube/cube.glb')
    vertices = []
    indices = []
    for tri in triangles:
        face = []
        for p,n in tri:
            row = p+n
            if row not in vertices: vertices.append(row)
            face.append(vertices.index(row))
        indices.append(face)
    return ('// Generated by tools/prepare_image_cube.py; mesh-local reference coordinates.\n'
            + f'pub const SOURCE_SHA256: &str = "{hashlib.sha256(raw).hexdigest()}";\n'
            + f'pub const VERTICES: [[f32; 6]; {len(vertices)}] = [\n'
            + ''.join('    ['+', '.join(repr(float(v)) for v in row)+'],\n' for row in vertices)
            + '];\n' + f'pub const TRIANGLES: [[usize; 3]; {len(indices)}] = [\n'
            + ''.join(f'    {row},\n' for row in indices) + '];\n')
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = ROOT/'src/image_cube.rs'
    if args.check:
        if target.read_text() != source(): raise SystemExit('stale image cube export')
    else: target.write_text(source())
